[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend --include=dev"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "cd backend && npx prisma generate"
]

[start]
cmd = "cd backend && npx prisma db push && node src/index.js"
